swupdate: add setup-nv-boot-control depends
Modify swupdate service to depend on setup-nv-boot-control
service, since without this service running the bootloader
script will fail to detect the correct slot.

Since swupdate service by default only depends on sysinit.target
and setup-nv-boot-control only is WantedBy muti-user.target in
[1] an ordering issue exists without the logic added here which
means the swupdate service can start too early.  When this happens,
any attempt to run nvbootctrl returns a failure message like:
```
Error: null input file!
```
and the select value of swupdate.conf is set to "system,slot_a"
on startup regardless of actual slot due to the logic in the
swupdate-genconfig script.  If the system is actually running from
slot b, the update will fail with a message like:
```
[ERROR] : SWUPDATE failed [0] ERROR mke2fs.c : ext_mkfs : 872 : Device or resource busy: while setting up superblock
[ERROR] : SWUPDATE failed [0] ERROR diskformat.c : diskformat_mkfs : 118 : creating ext4 file system on /dev/disk/by-partlabel/APP_b failed. -14
```

This likely relates to the issue noted in [2]

1: https://github.com/OE4T/meta-tegra/blob/54122711c9f4a01efa23530a0df1c6cdb47abbc5/recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.service.in#L15
2: https://github.com/orgs/OE4T/discussions/1634

Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>