swupdate-image-tegra: fix DTBFILE reference
DTBFILE definition was removed with [1], so add it
here in the swupdate-image-tegra recipe instead.

Resolves
```
ERROR: swupdate-image-tegra-1.0-r0 do_swuimage: swupdate cannot find devicetree/${DTBFILE} image file
```

1: https://github.com/OE4T/meta-tegra/commit/97066c019a9a3a4b6537b25bd2f55953328fba30
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>